version : '2'
services:
    intellij:
        build: .
        environment:
            - DISPLAY=:0
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix
            - ~/Documents/Programmation:/home/developer/prog
            - ~/.m2:/home/developer/.m2
            - ~/.IntelliJIdea2017.2:/home/developer/.IntelliJIdea2017.2
    licence-server:
        image: gaelrottier/idea-licence-server
        ports:
            - 1017:1017
